# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='media/images/person/')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\uace0\uac1d',
                'verbose_name_plural': '\uace0\uac1d \ub9ac\uc2a4\ud2b8',
            },
        ),
    ]
